#!/bin/sh

DATE=`(date +'%Y-%m-%d')`
TIME=`(date +'%H:%M')`
FOLDER="/Users/nehe/Documents/blog"
### idea? function call to automatically create file name with date in specified folder

if [ $# -lt 1 ]
then 
        TITLE="$DATE"

else
        TITLE="$1"
fi


SLUG=$(echo "${TITLE}" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)

# if folder doesn't exist
if [ ! -f "$FOLDER/$SLUG.md" ]
then 
        echo "---"                   >> $FOLDER/$SLUG.md
        echo "title: $TITLE"         >> $FOLDER/$SLUG.md
        echo "date: $DATE $TIME"     >> $FOLDER/$SLUG.md
        echo "modified: $DATE $TIME" >> $FOLDER/$SLUG.md
        echo "status: "              >> $FOLDER/$SLUG.md
        echo "---"                   >> $FOLDER/$SLUG.md
        echo ""                      >> $FOLDER/$SLUG.md
        echo ""                      >> $FOLDER/$SLUG.md
fi

${EDITOR} + $FOLDER/$SLUG.md # vi + file.md -- open file with vi at EOF


