#!/bin/sh

DATE=`(date +'%Y-%m-%d')`
FOLDER="/home/nehe/doc/blog"
### idea? function call to automatically create file name with date in specified folder

if [ $# -lt 1 ]
then 
        TITLE="$DATE"

else
        TITLE="$1"
fi


## SLUG=$(echo "${TITLE}" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)

# if folder doesn't exist
if [ ! -f "$FOLDER/$TITLE.md" ]
then 
        echo "title: $TITLE" >>  $FOLDER/$TITLE.md
        echo "date: $DATE" >> $FOLDER/$TITLE.md
        echo "modified: $DATE" >> $FOLDER/$TITLE.md
        echo "status: "     >> $FOLDER/$TITLE.md
        echo ""              >> $FOLDER/$TITLE.md
        echo ""              >> $FOLDER/$TITLE.md
fi

${EDITOR} + $FOLDER/$TITLE.md # vi + file.md -- open file with vi at EOF


