#!/usr/bin/env python3

######## POEM OF THE DAY ##########

""" script to query poetryfoundation to print a poem on your term """

import sys, os
import requests
from bs4 import BeautifulSoup 

url = "https://www.poetryfoundation.org/poems/poem-of-the-day"
page = requests.get(url).text

# Turn page into BeautifulSoup object to access HTML tags
soup = BeautifulSoup(page, features="lxml")
feature = soup.find(class_ = "c-feature")

title = " ".join(feature.find("h1").get_text().split())
author = feature.find("a").get_text()
poem = feature.find(class_ = "o-poem").find_all("div")

poem = "\n".join([line.get_text() for line in poem])

print()
print(title)
print()
print(author)
print("-------------------")
print()
print(poem)
print("-------------------")

