#!/bin/sh
# open question file from anywhere...


DATE=`(date +'%Y-%m-%d')`
FILE="/home/nehe/doc/question"

#if [$(tail -1 $FILE) ==  $DATE]
#then 
        echo "== $DATE =======" >> $FILE
        echo ""                 >> $FILE
#fi

${EDITOR} + $FILE
