#!/usr/bin/env python3

import sys
import time


def timer() -> None:
    try:
        start_time = time.perf_counter()
        while True:
            seconds = int(time.perf_counter() - start_time)
            clock = f"{int(seconds / 60):0>2}:{int(seconds % 60):0>2}"
            sys.stdout.write("\r")
            sys.stdout.write(clock)
            sys.stdout.flush()
            time.sleep(1)

    except KeyboardInterrupt:
        print("\nbye!")

    except Exception as ex:
        print(ex)
        exit(1)


timer()
