#!/usr/bin/env python3

import sys
import json
import pprint

word = sys.argv[1]

with open('/home/nehe/doc/webster/dictionary.json', 'r') as f:
    dictionary = json.load(f)

    if word not in dictionary:
        print(f"{word} not found.")
    else:
        pprint.pprint(dictionary[word].splitlines())
